# Generated by Django 3.0.3 on 2020-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200402_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
