# Generated by Django 3.0.3 on 2020-04-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_views'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
