# Generated by Django 3.0.3 on 2020-06-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagicApiData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_id', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('news_datePublished', models.DateTimeField(auto_now_add=True)),
                ('news_id', models.CharField(max_length=10)),
                ('news_title', models.CharField(max_length=100)),
                ('news_summary', models.TextField()),
                ('news_url', models.CharField(max_length=100)),
                ('news_contact', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
