# Generated by Django 3.0.3 on 2020-06-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bagicapidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagicapidata',
            name='news_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
