# Generated by Django 3.0.3 on 2020-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bagicapidata_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagicapidata',
            name='identifier',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='bagicapidata',
            name='lang_code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
