# Generated by Django 3.0.3 on 2020-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200604_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagicapidata',
            name='news_id',
            field=models.CharField(max_length=10),
        ),
    ]
