# Generated by Django 3.0.3 on 2020-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200605_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagicapidata',
            name='identifier',
            field=models.CharField(default='', max_length=30),
        ),
    ]
