# Generated by Django 3.0.3 on 2020-06-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200605_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagicNewsTagMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False, max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bagicapidata',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.BagicNewsTagMaster'),
        ),
    ]
