# Generated by Django 3.0.3 on 2020-06-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200625_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BagicNewsTagMaster',
            new_name='BagicTagMaster',
        ),
    ]
