# Generated by Django 3.0.3 on 2020-06-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200625_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagicapidata',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BagicTagMaster'),
        ),
    ]
