# Generated by Django 3.0.3 on 2020-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200625_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagicapidata',
            name='sub_category',
            field=models.IntegerField(),
        ),
    ]
